const itineraryData = [
  {
    "day": 1,
    "date": "Dec 12 (Sat)",
    "title": "Gateway Arrival & AWD SUV Pickup",
    "location": "Rovaniemi, Finland",
    "coords": [66.5039, 25.7294],
    "distance": "10 km (15 mins)",
    "hotel": "Rovaniemi Central (Pending Confirmation)",
    "hotelStatus": "pending",
    "bookingRef": "Unconfirmed in Folder",
    "activities": "Fly SIN -> MUC -> RVN (Arrive 5:15 PM); pick up AWD SUV rental; evening walk in central Rovaniemi; dinner at Nili / Gustav.",
    "scheduleNotes": "Gateway Arrival & AWD SUV Pickup",
    "tags": ["Flight Arrival", "SUV Rental Pickup", "Rovaniemi Dinner"]
  },
  {
    "day": 2,
    "date": "Dec 13 (Sun)",
    "title": "Sweden Border Crossing & Torne Valley",
    "location": "Harads / Storklinten, Sweden",
    "coords": [65.8252, 21.6886],
    "distance": "235 km (2h 45m)",
    "hotel": "Stuga i Storklinten (Boden)",
    "hotelStatus": "confirmed",
    "bookingRef": "Booking.com (Check-in 13 Dec - Check-out 15 Dec)",
    "activities": "Drive west through Torne Valley; cross border at Tornio-Haparanda; stop at frozen Kukkolankoski river rapids; check into cabin/lodge; evening sauna & Nordic dinner.",
    "scheduleNotes": "Sweden Border Crossing & Torne Valley",
    "tags": ["Cross Border", "Torne Valley", "Storklinten Sauna"]
  },
  {
    "day": 3,
    "date": "Dec 14 (Mon)",
    "title": "Zero-Driving Rest & Nature Day",
    "location": "Harads / Storklinten, Sweden",
    "coords": [65.8252, 21.6886],
    "distance": "0 km (0h - Rest Day)",
    "hotel": "Stuga i Storklinten (Boden)",
    "hotelStatus": "confirmed",
    "bookingRef": "Booking.com (Night 2 of 2)",
    "activities": "Arctic wellness & snow day; outdoor snowshoeing / cross-country skiing through pine forests; wood-fired saunas & cold plunge; night aurora watching.",
    "scheduleNotes": "Zero-Driving Rest & Nature Day",
    "tags": ["Rest Day", "Snowshoeing", "Wood-fired Sauna", "Aurora Spotting"]
  },
  {
    "day": 4,
    "date": "Dec 15 (Tue)",
    "title": "ICEHOTEL 37 Opening Week & Sámi Reindeer",
    "location": "Jukkasjärvi / Kiruna, Sweden",
    "coords": [67.8557, 20.2253],
    "distance": "280 km (3h 30m)",
    "hotel": "Northernlight cabin (Kiruna)",
    "hotelStatus": "confirmed",
    "bookingRef": "Booking.com (Check-in 15 Dec - Check-out 16 Dec)",
    "activities": "Drive north across Swedish Lapland tundra; tour freshly opened ICEHOTEL 37 hand-carved ice art suites & ice chapel (opens Dec 11); drink at original Icebar; reindeer feeding at Nutti Sámi Siida.",
    "scheduleNotes": "ICEHOTEL 37 Opening Week & Sámi Reindeer",
    "tags": ["ICEHOTEL 37", "Icebar", "Sámi Culture", "Reindeer Feeding"]
  },
  {
    "day": 5,
    "date": "Dec 16 (Wed)",
    "title": "Abisko National Park & Aurora Sky Station Night 1",
    "location": "Abisko / Björkliden, Sweden",
    "coords": [68.4064, 18.6811],
    "distance": "100 km (1h 15m)",
    "hotel": "Aurora View Apt – Walk to Train & Ski (Björkliden)",
    "hotelStatus": "confirmed",
    "bookingRef": "Airbnb Ref: HM2B8KDQ4H (Host: Renberget, Check-in 16 Dec - Check-out 19 Dec)",
    "activities": "Scenic mountain drive along Lake Torneträsk; explore Abisko Canyon frozen waterfalls; night open-chairlift ride to mountaintop Aurora Sky Station on Mount Nuolja.",
    "scheduleNotes": "Abisko National Park & Aurora Sky Station Night 1",
    "tags": ["Lake Torneträsk", "Abisko Canyon", "Aurora Sky Station", "Mt Nuolja"]
  },
  {
    "day": 6,
    "date": "Dec 17 (Thu)",
    "title": "Zero-Driving Alpine Tundra & Aurora Blue Hole Night 2",
    "location": "Abisko / Björkliden, Sweden",
    "coords": [68.4064, 18.6811],
    "distance": "0 km (0h - Rest Day)",
    "hotel": "Aurora View Apt – Walk to Train & Ski (Björkliden)",
    "hotelStatus": "confirmed",
    "bookingRef": "Airbnb Ref: HM2B8KDQ4H (Night 2 of 3)",
    "activities": "Guided alpine snowmobile safari across mountain passes toward the Norwegian border (Riksgränsen); marvel at Lapporten U-shaped valley; night aurora watch at Lake Torneträsk shores.",
    "scheduleNotes": "Zero-Driving Alpine Tundra & Aurora Blue Hole Night 2",
    "tags": ["Snowmobile Safari", "Riksgränsen", "Lapporten Valley", "Aurora Blue Hole"]
  },
  {
    "day": 7,
    "date": "Dec 18 (Fri)",
    "title": "Zero-Driving Husky Safari & Peak Aurora Night 3",
    "location": "Abisko / Björkliden, Sweden",
    "coords": [68.4064, 18.6811],
    "distance": "0 km (0h - Rest Day)",
    "hotel": "Aurora View Apt – Walk to Train & Ski (Björkliden)",
    "hotelStatus": "confirmed",
    "bookingRef": "Airbnb Ref: HM2B8KDQ4H (Night 3 of 3)",
    "activities": "Morning 3-hour husky sledding safari through Arctic birch forest; visit Silverfallet frozen waterfall beach; dinner at Abisko Mountain Lodge; night aurora watch.",
    "scheduleNotes": "Zero-Driving Husky Safari & Peak Aurora Night 3",
    "tags": ["Husky Safari", "Silverfallet Waterfall", "Abisko Mountain Lodge"]
  },
  {
    "day": 8,
    "date": "Dec 19 (Sat)",
    "title": "Finland Re-entry & SnowCastle of Kemi",
    "location": "Kemi, Finland",
    "coords": [65.7363, 24.5637],
    "distance": "340 km (4h 00m)",
    "hotel": "Cozy Apartment by the Sea 2 Rooms (Kemi)",
    "hotelStatus": "confirmed",
    "bookingRef": "Booking.com (Check-in 19 Dec - Check-out 21 Dec)",
    "activities": "Scenic cross-border drive south from Swedish mountains to Finnish Bothnian coast; cross border at Tornio; check in; explore SnowExperience365 indoor ice castle and ice bar.",
    "scheduleNotes": "Finland Re-entry & SnowCastle of Kemi",
    "tags": ["Cross Border", "Bothnian Coast", "SnowExperience365", "Ice Castle"]
  },
  {
    "day": 9,
    "date": "Dec 20 (Sun)",
    "title": "Sampo Icebreaker Cruise & Sea Ice Floating",
    "location": "Kemi, Finland",
    "coords": [65.7363, 24.5637],
    "distance": "20 km (20m local)",
    "hotel": "Cozy Apartment by the Sea 2 Rooms (Kemi)",
    "hotelStatus": "confirmed",
    "bookingRef": "Booking.com (Night 2 of 2)",
    "activities": "Official Sampo Icebreaker Cruise (operational season starts Dec 18!): crush through solid sea ice, engine room tour, survival drysuit floating in open sea-ice pool; coastal sauna.",
    "scheduleNotes": "Sampo Icebreaker Cruise & Sea Ice Floating",
    "tags": ["Sampo Icebreaker", "Drysuit Floating", "Frozen Sea Ice", "Coastal Sauna"]
  },
  {
    "day": 10,
    "date": "Dec 21 (Mon)",
    "title": "Check-in Rantapolku 1 Posio",
    "location": "Posio, Finland",
    "coords": [66.1089, 28.1633],
    "distance": "170 km (2h 15m)",
    "hotel": "Idyllic sauna cottage by the lake (Rantapolku 1, Posio)",
    "hotelStatus": "confirmed",
    "bookingRef": "Airbnb Ref: HMYPAMHXW9 (Host: Leena, Check-in 21 Dec - Check-out 23 Dec)",
    "activities": "Scenic drive east to Posio; stop at S-Market Posio for groceries; check into Airbnb (Rantapolku 1); evening lakeside sauna & quiet aurora watch.",
    "scheduleNotes": "Check-in Rantapolku 1 Posio (Airbnb Booked)",
    "tags": ["Posio Cottage", "Lakeside Sauna", "Local Groceries", "Quiet Aurora"]
  },
  {
    "day": 11,
    "date": "Dec 22 (Tue)",
    "title": "Riisitunturi National Park World-Class Tykky Trees",
    "location": "Posio, Finland",
    "coords": [66.1089, 28.1633],
    "distance": "60 km (50m roundtrip)",
    "hotel": "Idyllic sauna cottage by the lake (Rantapolku 1, Posio)",
    "hotelStatus": "confirmed",
    "bookingRef": "Airbnb Ref: HMYPAMHXW9 (Night 2 of 2)",
    "activities": "25-minute drive to Riisitunturi National Park; 10:30 AM golden twilight snowshoe hike (Riisin rääpäsy 4.3 km trail) among Europe's heaviest Tykky snow-sculpture trees; campfire lunch at wilderness hut.",
    "scheduleNotes": "Riisitunturi National Park World-Class Tykky Trees",
    "tags": ["Riisitunturi", "Tykky Snow Trees", "Golden Twilight Hike", "Campfire Lunch"]
  },
  {
    "day": 12,
    "date": "Dec 23 (Wed)",
    "title": "Easy 1h Hop to Iso-Syöte Fell",
    "location": "Iso-Syöte, Finland",
    "coords": [65.6265, 27.6083],
    "distance": "75 km (55 mins)",
    "hotel": "Apartment at top of Iso-Syöte (Host Arto - Pending Dates)",
    "hotelStatus": "shortlisted",
    "bookingRef": "Airbnb Listing saved (Confirmation receipt pending)",
    "activities": "Relaxed morning in Posio; short 55-minute drive to Iso-Syöte fell summit; check in; afternoon downhill skiing or panoramic fell-top spa; dinner at Restaurant Hilltop.",
    "scheduleNotes": "Easy 1h Hop to Iso-Syöte Fell",
    "tags": ["Fell Summit", "Downhill Skiing", "Fell-top Spa", "Restaurant Hilltop"]
  },
  {
    "day": 13,
    "date": "Dec 24 (Thu)",
    "title": "Confirmed Booking: Iso-Syöte Treehouse / Igloo (Christmas Eve)",
    "location": "Iso-Syöte, Finland",
    "coords": [65.6265, 27.6083],
    "distance": "0 km (0h - Rest Day)",
    "hotel": "Syöte Igloos / Iso-Syöte Treehouse",
    "hotelStatus": "confirmed",
    "bookingRef": "Booking.com (Check-in 24 Dec - Check-out 25 Dec)",
    "activities": "Check into your confirmed Iso-Syöte Treehouse / Igloo (luggage transferred across path); Christmas Eve feast, private fell-top sauna, panoramic glass view of snow-covered spruce canopy.",
    "scheduleNotes": "Confirmed Booking: Iso-Syöte Treehouse / Igloos (Christmas Eve)",
    "tags": ["Christmas Eve", "Glass Igloo / Treehouse", "Private Sauna", "Holiday Feast"]
  },
  {
    "day": 14,
    "date": "Dec 25 (Fri)",
    "title": "Santa Claus Village & VR Express Sleeper Train",
    "location": "En-Route VR Night Train",
    "coords": [66.5039, 25.7294],
    "distance": "160 km (2h 00m)",
    "hotel": "VR Santa Claus Express Sleeper Train (9:00 PM)",
    "hotelStatus": "confirmed",
    "bookingRef": "VR Train Booking (Rovaniemi -> Helsinki Central)",
    "activities": "Christmas Day morning at Iso-Syöte; drive to Rovaniemi; explore Santa Claus Village & post office; return AWD SUV at station ($0 drop-off fee); board 9:00 PM VR Santa Claus Express Sleeper Train.",
    "scheduleNotes": "Confirmed Booking: VR Sleeper Train 9:00 PM",
    "tags": ["Santa Claus Village", "Post Office", "SUV Return", "VR Sleeper Train"]
  },
  {
    "day": 15,
    "date": "Dec 26 (Sat)",
    "title": "Helsinki Boxing Day & Löyly Smoke Sauna",
    "location": "Helsinki, Finland",
    "coords": [60.1699, 24.9384],
    "distance": "0 km (Transit)",
    "hotel": "Hotel U14 Autograph Collection",
    "hotelStatus": "confirmed",
    "bookingRef": "Confirmed Hotel U14 Autograph Collection",
    "activities": "Arrive Helsinki Central 9:00 AM (Boxing Day); explore Oodi Central Library & Senate Square; afternoon seaside smoke sauna & Baltic ice dip at Löyly.",
    "scheduleNotes": "Confirmed Booking: Hotel U14 Autograph Collection",
    "tags": ["Oodi Library", "Senate Square", "Löyly Sauna", "Baltic Ice Dip"]
  },
  {
    "day": 16,
    "date": "Dec 27 (Sun)",
    "title": "Baltic Sea Ferry Transit & Medieval Tallinn",
    "location": "Tallinn, Estonia",
    "coords": [59.4370, 24.7536],
    "distance": "0 km (Ferry)",
    "hotel": "Old Town Tallinn Hotel (Pending Booking)",
    "hotelStatus": "pending",
    "bookingRef": "Pending PDF Confirmation",
    "activities": "Morning 2-hour Megastar express ferry across Baltic Sea; explore UNESCO medieval Old Town, Town Hall Christmas Market, and Toompea Hill vista.",
    "scheduleNotes": "Baltic Sea Ferry Transit & Medieval Tallinn",
    "tags": ["Megastar Ferry", "UNESCO Old Town", "Christmas Market", "Toompea Hill"]
  },
  {
    "day": 17,
    "date": "Dec 28 (Mon)",
    "title": "Flight TLL -> ARN to Stockholm",
    "location": "Stockholm, Sweden",
    "coords": [59.3293, 18.0686],
    "distance": "0 km (Flight)",
    "hotel": "Stockholm Central Hotel (Pending Booking)",
    "hotelStatus": "pending",
    "bookingRef": "Pending PDF Confirmation",
    "activities": "Morning visit to Kadriorg Palace or Seaplane Harbour; late afternoon flight to Stockholm (TLL -> ARN); evening walk through illuminated Norrmalm & Nybroplan.",
    "scheduleNotes": "Flight TLL -> ARN to Stockholm",
    "tags": ["Kadriorg Palace", "Flight TLL-ARN", "Norrmalm", "Nybroplan Illuminations"]
  },
  {
    "day": 18,
    "date": "Dec 29 (Tue)",
    "title": "Stockholm Core Day 1",
    "location": "Stockholm, Sweden",
    "coords": [59.3293, 18.0686],
    "distance": "0 km (Metro/Walk)",
    "hotel": "Stockholm Central Hotel (Pending Booking)",
    "hotelStatus": "pending",
    "bookingRef": "Pending PDF Confirmation",
    "activities": "Full day of historic Stockholm: cobblestone alleys of Gamla Stan (Old Town), Royal Palace, Stortorget, and Nobel Prize Museum.",
    "scheduleNotes": "Stockholm Core Day 1",
    "tags": ["Gamla Stan", "Royal Palace", "Stortorget", "Nobel Prize Museum"]
  },
  {
    "day": 19,
    "date": "Dec 30 (Wed)",
    "title": "Stockholm Core Day 2",
    "location": "Stockholm, Sweden",
    "coords": [59.3293, 18.0686],
    "distance": "0 km (Ferry/Tram)",
    "hotel": "Stockholm Central Hotel (Pending Booking)",
    "hotelStatus": "pending",
    "bookingRef": "Pending PDF Confirmation",
    "activities": "Maritime & culture day: tour 17th-century Vasa Museum, explore Djurgården island & Skansen, or visit ABBA The Museum; traditional Swedish dinner.",
    "scheduleNotes": "Stockholm Core Day 2",
    "tags": ["Vasa Museum", "Djurgården", "Skansen", "ABBA Museum"]
  },
  {
    "day": 20,
    "date": "Dec 31 (Thu)",
    "title": "High-Speed Train & NYE Tivoli Celebration",
    "location": "Copenhagen, Denmark",
    "coords": [55.6761, 12.5683],
    "distance": "0 km (Train)",
    "hotel": "Copenhagen Central Hotel (Pending Booking)",
    "hotelStatus": "pending",
    "bookingRef": "Pending PDF Confirmation",
    "activities": "Morning SJ High-Speed Train from Stockholm Central to Copenhagen Central (5h 10m via Öresund Bridge); check in; New Year's Eve gala dinner & midnight fireworks at Tivoli Gardens.",
    "scheduleNotes": "High-Speed Train & NYE Tivoli Celebration",
    "tags": ["SJ High-Speed Train", "Öresund Bridge", "NYE Gala", "Tivoli Fireworks"]
  },
  {
    "day": 21,
    "date": "Jan 01 (Fri)",
    "title": "New Year's Day in Copenhagen",
    "location": "Copenhagen, Denmark",
    "coords": [55.6761, 12.5683],
    "distance": "0 km (Metro/Walk)",
    "hotel": "Copenhagen Central Hotel (Pending Booking)",
    "hotelStatus": "pending",
    "bookingRef": "Pending PDF Confirmation",
    "activities": "Relaxed New Year's Day stroll; view CopenHill rooftop architecture, Amalienborg Palace royal guard change, and Nyhavn / Strøget cafe culture.",
    "scheduleNotes": "New Year's Day in Copenhagen",
    "tags": ["CopenHill", "Amalienborg Palace", "Nyhavn", "Strøget Cafe Culture"]
  },
  {
    "day": 22,
    "date": "Jan 02 (Sat)",
    "title": "SQ352 Non-stop to Singapore",
    "location": "Flight Home (In Flight)",
    "coords": [55.6180, 12.6508],
    "distance": "0 km (Metro)",
    "hotel": "In Flight (Singapore Airlines SQ352)",
    "hotelStatus": "confirmed",
    "bookingRef": "SQ352 Non-stop (Dep CPH 12:00 PM, Arr SIN Jan 03 7:30 AM)",
    "activities": "Morning 13-minute Metro to CPH Airport; depart on Singapore Airlines SQ352 non-stop to Singapore at 12:00 PM (Arrive SIN Jan 03, 7:30 AM).",
    "scheduleNotes": "SQ352 Non-stop to Singapore",
    "tags": ["Metro to CPH", "SQ352 Non-stop", "Singapore Flight"]
  }
];
